// solid-ts/src/lib/hooks.ts
import { onCleanup, createSignal, createEffect } from 'solid-js';
import { noop } from './constants';

export const dragScroll = (slider: HTMLElement): void => {
	let isDown = false;
	let startX: number;
	let scrollLeft: number;

	const handleMouseDown = (e: MouseEvent): void => {
		isDown = true;
		startX = e.pageX - slider.getBoundingClientRect().left;
		scrollLeft = slider.scrollLeft;
	};

	const handleMouseUp = () => (isDown = false);
	const handleMouseLeave = () => (isDown = false);

	const handleMouseMove = ({ pageX, preventDefault }: MouseEvent): void => {
		if (!isDown) return;

		preventDefault();

		slider.scrollLeft =
			scrollLeft - (pageX - slider.getBoundingClientRect().left - startX);
	};

	slider.addEventListener('mousedown', handleMouseDown);
	slider.addEventListener('mouseup', handleMouseUp);
	slider.addEventListener('mouseleave', handleMouseLeave);
	slider.addEventListener('mousemove', handleMouseMove);
	slider.classList.add('scroll-drag');

	onCleanup(() => {
		slider.removeEventListener('mousedown', handleMouseDown);
		slider.removeEventListener('mouseup', handleMouseUp);
		slider.removeEventListener('mouseleave', handleMouseLeave);
		slider.removeEventListener('mousemove', handleMouseMove);
		slider.classList.remove('scroll-drag');
	});
};

export const useNuiEvent = <T = any>(
	action: string,
	handler: NuiHandlerSignature<T>,
) => {
	const [savedHandler, setSavedHandler] =
		createSignal<NuiHandlerSignature<T>>(noop);

	createEffect(() => {
		setSavedHandler(() => handler);
	});

	createEffect(() => {
		const eventListener = (event: MessageEvent): void => {
			const { data } = event;

			if (savedHandler() && data.action === action)
				savedHandler()(data.data as T);
		};

		window.addEventListener('message', eventListener);
		onCleanup(() => window.removeEventListener('message', eventListener));
	});
};

// react-ts/src/utils/hooks.ts
import { MutableRefObject, useEffect, useRef } from 'react';
import { noop } from '.';

export const useDragScroll = (slider: HTMLElement) => {
	let isDown = false;
	let startX: number;
	let scrollLeft: number;

	slider.addEventListener('mousedown', (e) => {
		isDown = true;
		startX = e.pageX - slider.offsetLeft;
		scrollLeft = slider.scrollLeft;
	});

	slider.addEventListener('mouseup', () => (isDown = false));
	slider.addEventListener('mouseleave', () => (isDown = false));

	slider.addEventListener('mousemove', (e) => {
		if (!isDown) return;
		e.preventDefault();
		const x = e.pageX - slider.offsetLeft;
		const walk = x - startX;
		slider.scrollLeft = scrollLeft - walk;
	});

	slider.classList.add('scroll-drag');
};

export const useNuiEvent = <T = any>(
	action: string,
	handler: (data: T) => void,
) => {
	const savedHandler: MutableRefObject<NuiHandlerSignature<T>> = useRef(noop);

	useEffect(() => {
		savedHandler.current = handler;
	}, [handler]);

	useEffect(() => {
		const eventListener = (event: MessageEvent) => {
			if (savedHandler.current) {
				if (event.data.action === action) {
					savedHandler.current(event.data.data as T);
				}
			}
		};

		window.addEventListener('message', eventListener);
		return () => window.removeEventListener('message', eventListener);
	}, [action]);
};

export const useKeyEvent = (
	key: string,
	handler: (data: KeyboardEvent) => void,
) => {
	const savedHandler: MutableRefObject<(e: KeyboardEvent) => any> =
		useRef(noop);

	useEffect(() => {
		savedHandler.current = handler;
	}, [handler]);

	useEffect(() => {
		const keyListener = (event: KeyboardEvent) => {
			if (savedHandler.current) {
				if (event.key === key) {
					savedHandler.current(event);
				}
			}
		};

		window.addEventListener('keydown', keyListener);
		return () =>
			window.removeEventListener('keydown', keyListener);
	}, [key]);
};
